version: '3.7'

# DCKHUB=devoinc/ docker-compose -f docker-devo-relay-stunnel.yml up -d
# Connect to Relay container: docker exec -it Devo-Relay /bin/bash
# Connect to Stunnel container: docker exec -it Devo-Stunnel /bin/bash
### Check RELAY:
# for i in $( seq 10 ) ; do echo "<14>$( date --iso-8601=seconds ) docker-relay test.keep.free: Docker message to Devo-Relay directly port 13000 - test event # $i" | nc -N Devo-Relay 13000 ; done
### Check STUNNEL:
# for i in $( seq 10 ) ; do echo "<14>$( date --iso-8601=seconds ) docker-stunnel test.keep.free: Docker message with stunnel to Relay - test event # $i"|openssl s_client -connect localhost:6615 -key /etc/pki/stunnel/server.key -cert /etc/pki/stunnel/server.crt; done
#####

networks:
  devoring:

services:
  Devo-Relay:
    image: ${DCKHUB}devo-relay:1.1.6
    hostname: Relay
    container_name: Devo-Relay
    restart: always
    environment:
      - DUMMYSTAT=0
      # UNCOMMENT THE NEXT ENVIROMENT VARIABLE TO USE RELAY IN Cloud/OnPREM with SELFSIGNED CERTS
      - SELFSIGNED=1
      # Set the right DEVO WEB in LOGTRUST_WEB va: eu.devo.com | us.devo.com | es.devo.com
      - LOGTRUST_WEB=https://eu.devo.com
      # Set the right end point for the choosed Devo cloud
      - LOGTRUST_ENDPOINT=eu.elb.relay.logtrust.net
      # Set the right secure port to send data to Devo
      - LOGTRUST_PORT=443
      # Set the name for the relay, usually relay-domain_name
      - RELAY_NAME=stunnel
      # Set valid APIKEY for the domain
      - RELAY_APIKEY=YOUR_API_KEY
      # Set proxy values if it's necessary in for your network. Default "" is not applied
      - PROXY_HOST=
      - PROXY_PORT=
      - PROXY_USER=
      - PROXY_PASS=
    ports:
     - 12999-13030:12999-13030
    volumes:
       ###App persisten information
       - ./conf/relay/docker-start:/opt/devo/docker-start
       - type: bind
         source: "./conf/relay/relay-data"
         target: "/opt/devo/relay-data"
       - type: bind
         source: "./conf/relay/rules"
         target: "/etc/logtrust/scoja/current/rules"
       - type: bind
         source: "./conf/relay/unrules"
         target: "/etc/logtrust/scoja/current/unrules"
       - type: bind
         source: "./conf/relay/keys"
         target: "/etc/logtrust/scoja/current/keys"
       - type: bind
         source: "./conf/logs/relay"
         target: "/var/log"
    networks:
       devoring:
         aliases:
           - DevoRelay
    # To debug comment the next line
    command: /opt/devo/docker-start
    logging:
      driver: none

  Devo-Stunnel:
    image: ${DCKHUB}devo-stunnel:5.44
    hostname: stunnel
    container_name: Devo-Stunnel
    restart: always
    environment:
      - DUMMYSTAT=0
    ports:
     - 6601-6650:6601-6650
    volumes:
       ###App persisten information
       - type: bind
         source: "./conf/stunnel/stunnel.conf"
         target: "/etc/stunnel/stunnel.conf"
       - type: bind
         source: "./conf/stunnel/certs"
         target: "/etc/pki/stunnel"
       - type: bind
         source: "./conf/logs/stunnel4"
         target: "/var/log/stunnel4"
    networks:
       devoring:
         aliases:
           - DevoStunnel
    # To debug uncomment the next line
    # command: "tail -F /root/docker_images_version.txt"
    logging:
      driver: none

### END
